import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { getAuth } from 'firebase/auth'
import { logout } from '@/actions/authActions'
import { useDispatch, useSelector } from 'react-redux'
import { withAuth } from '../utils/withAuth'
import FullscreenLoading from '@/components/FullscreenLoading'
import { useEffect, useState } from 'react'
import { toast } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] })

 function Home() {
  
  const dispatch = useDispatch();
  const isLoading = useSelector(state => state.auth);
  //const error = useSelector(state => state.auth.error);
  const [Loading,setLoading] = useState(true)
  
  const error = useSelector((state) => state);

  useEffect(() => {
    if (error) {
      toast.error(error.message);
    }
  }, [error]);


  const handleSignout = (e) => {
    e.preventDefault();
    dispatch(logout());
  }
  useEffect(() => {
    setTimeout(() => {
      setLoading(false)
    }, 3000); // change duration to adjust how long the animation should last

    
  }, []);

  if(Loading){
    return <FullscreenLoading/>
  }
  const handleClick = () => {
    toast.success('This is a success message!', {
      position: toast.POSITION.TOP_RIGHT,
      autoClose: 3000,
      hideProgressBar: false,
      closeOnClick: true,
      pauseOnHover: true,
      draggable: true,
    });
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={handleSignout} className='btn btn-info' >Logout</button>
        <button className='btn btn-info' onClick={handleClick}>Show Toast</button>
      </main>
    </>
  )
}

export default withAuth(Home)
